//! Rendering tests.
//!
//! These are pure: nothing here talks to herdr or to git. Every fixture is a
//! hand-built `Digest`, and every assertion is about the text that comes out.
//!
//! Two rules were followed deliberately, because they are what makes these
//! tests worth having:
//!
//! 1. **No golden strings taken from the implementation.** A golden file
//!    generated by running the renderer proves only that the renderer is
//!    deterministic. Every assertion below names the *content* it wants — a
//!    number, a word, a relationship between two lines — and none of them was
//!    copied out of a run.
//! 2. **Widths are checked in display columns, never in bytes.** The output
//!    contains `…`, `·` and `−`, so `str::len` would report 3 columns for one.
//!    The `columns` helper is a second, independent implementation of the width
//!    rule, so a bug in the renderer's own width code cannot hide behind a
//!    matching bug here.

use std::path::PathBuf;

use standup::config::Config;
use standup::model::{
    AgentRef, CheckoutDigest, CheckoutReport, Churn, Commit, Digest, Dirty, Equivalence, Head,
    Landed, Note, RepoDigest, RepoKey, Stamp, Tracking, Window, WindowSource, WorkspaceRef,
    SCHEMA_VERSION,
};
use standup::render::{json, markdown, text};

/// The minus sign the renderers use, which is not a hyphen.
const MINUS: &str = "\u{2212}";
const ELLIPSIS: &str = "\u{2026}";
/// The multiplication sign that counts repeated agent labels, not the letter x.
const TIMES: &str = "\u{d7}";
const ZONE: &str = "CEST +0200";
const WIDTH: usize = 80;

// ---------------------------------------------------------------------------
// Test-local display width
// ---------------------------------------------------------------------------

/// Width of `text` in terminal columns, written from scratch rather than
/// reusing the renderer's own.
fn columns(text: &str) -> usize {
    let mut total = 0;
    for ch in text.chars() {
        if ch.is_control() {
            continue;
        }
        total += match ch as u32 {
            0x0300..=0x036f | 0x200b..=0x200f | 0xfe00..=0xfe0f | 0xfeff => 0,
            0x1100..=0x115f
            | 0x2e80..=0xa4cf
            | 0xac00..=0xd7a3
            | 0xf900..=0xfaff
            | 0xfe30..=0xfe6f
            | 0xff00..=0xff60
            | 0xffe0..=0xffe6
            | 0x1f300..=0x1f64f
            | 0x1f900..=0x1f9ff => 2,
            _ => 1,
        };
    }
    total
}

fn widest(text: &str) -> usize {
    text.lines().map(columns).max().unwrap_or(0)
}

/// The whole report as one whitespace-normalised line, for asserting on prose
/// that wraps differently depending on what is around it.
fn flatten(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// The line that mentions `needle`, for assertions about one row's shape.
fn line_with<'a>(text: &'a str, needle: &str) -> &'a str {
    text.lines()
        .find(|line| line.contains(needle))
        .unwrap_or_else(|| panic!("no line containing {needle:?} in:\n{text}"))
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

fn stamp(local: &str, epoch: i64) -> Stamp {
    Stamp {
        epoch,
        local: local.to_string(),
        zone: ZONE.to_string(),
    }
}

/// The ordinary case: a window opened at local midnight today, still running.
fn today() -> Window {
    Window {
        since: stamp("2026-08-15 00:00", 1_786_000_000),
        until: None,
        source: WindowSource::Default,
    }
}

fn commit(oid: &str, local: &str, epoch: i64, subject: &str, files: &[&str]) -> Commit {
    Commit {
        oid: oid.to_string(),
        author: "Agent Smith".to_string(),
        committed: stamp(local, epoch),
        subject: subject.to_string(),
        is_merge: false,
        insertions: 10,
        deletions: 4,
        files: files.iter().map(|f| f.to_string()).collect(),
    }
}

/// A checkout with nothing to say: on a branch, clean, no commits.
fn checkout(path: &str, branch: &str) -> CheckoutReport {
    CheckoutReport {
        path: PathBuf::from(path),
        repo_key: RepoKey("/repos/app/.git".to_string()),
        repo_root: PathBuf::from("/repos/app"),
        is_linked_worktree: false,
        head: Head::Branch {
            name: branch.to_string(),
            oid: "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678".to_string(),
        },
        commits: Vec::new(),
        churn: Churn::default(),
        dirty: Dirty::default(),
        tracking: Tracking::NoUpstream,
        landed: Landed::Unknown {
            reason: "no default branch to compare against".to_string(),
        },
        problems: Vec::new(),
    }
}

/// Attaches commits and the churn they imply, the way `git.rs` would.
fn with_commits(mut report: CheckoutReport, commits: Vec<Commit>) -> CheckoutReport {
    let mut churn = Churn::default();
    let mut files: Vec<&str> = Vec::new();
    for commit in &commits {
        churn.insertions += commit.insertions;
        churn.deletions += commit.deletions;
        for file in &commit.files {
            if !files.contains(&file.as_str()) {
                files.push(file);
            }
        }
    }
    churn.files = files.len();
    report.commits = commits;
    report.churn = churn;
    report
}

fn alone(report: CheckoutReport) -> CheckoutDigest {
    CheckoutDigest {
        report,
        workspaces: Vec::new(),
        agents: Vec::new(),
    }
}

/// One agent in one pane. The pane is explicit because it is the identity: two
/// agents can share a display label and still be two agents, which is #19.
fn agent(pane: &str, name: Option<&str>, program: Option<&str>) -> AgentRef {
    AgentRef {
        name: name.map(str::to_string),
        program: program.map(str::to_string),
        session_id: Some("session-7f3a".to_string()),
        pane_id: pane.to_string(),
        status: Some("working".to_string()),
        cwd: Some(PathBuf::from("/repos/app")),
    }
}

/// A checkout whose agents herdr placed here, which is what the renderer
/// credits. The workspace roster is carried alongside and is not the
/// attribution.
fn worked_by(report: CheckoutReport, agents: Vec<AgentRef>) -> CheckoutDigest {
    CheckoutDigest {
        report,
        workspaces: vec![workspace("media", agents.clone())],
        agents,
    }
}

fn workspace(label: &str, agents: Vec<AgentRef>) -> WorkspaceRef {
    WorkspaceRef {
        workspace_id: format!("ws-{label}"),
        label: label.to_string(),
        number: Some(3),
        paths: vec![PathBuf::from("/repos/app")],
        agents,
        agent_status: Some("working".to_string()),
    }
}

/// A repository with the same rollup rule `standup::build` applies: distinct
/// commit ids, and the union of touched paths.
fn repo(name: &str, checkouts: Vec<CheckoutDigest>) -> RepoDigest {
    let mut seen: Vec<String> = Vec::new();
    let mut files: Vec<String> = Vec::new();
    let mut churn = Churn::default();
    for checkout in &checkouts {
        for commit in &checkout.report.commits {
            if seen.contains(&commit.oid) {
                continue;
            }
            seen.push(commit.oid.clone());
            churn.insertions += commit.insertions;
            churn.deletions += commit.deletions;
            for file in &commit.files {
                if !files.contains(file) {
                    files.push(file.clone());
                }
            }
        }
    }
    churn.files = files.len();
    RepoDigest {
        repo_key: RepoKey(format!("/repos/{name}/.git")),
        name: name.to_string(),
        repo_root: PathBuf::from(format!("/repos/{name}")),
        checkouts,
        commits: seen.len(),
        churn,
    }
}

fn quiet_repo(name: &str) -> RepoDigest {
    repo(
        name,
        vec![alone(checkout(&format!("/repos/{name}"), "main"))],
    )
}

fn digest(repos: Vec<RepoDigest>, notes: Vec<Note>) -> Digest {
    Digest {
        schema: SCHEMA_VERSION,
        generated_at: stamp("2026-08-15 09:12", 1_786_033_920),
        window: today(),
        repos,
        notes,
    }
}

/// One busy repository, used wherever the test is about something else.
fn busy_repo() -> RepoDigest {
    let report = with_commits(
        checkout("/repos/lanternfish", "fix/media-fetch-throughput"),
        vec![
            commit(
                "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678",
                "2026-08-15 09:04",
                1_786_032_240,
                "Batch media fetches behind a semaphore",
                &["src/media.rs", "src/lib.rs"],
            ),
            commit(
                "b2c3d4e5f60718293a4b5c6d7e8f901234567890",
                "2026-08-15 08:31",
                1_786_030_260,
                "Add a throughput regression test",
                &["tests/media.rs"],
            ),
        ],
    );
    repo("lanternfish", vec![alone(report)])
}

fn plain(digest: &Digest) -> String {
    text(digest, &Config::default())
}

fn md(digest: &Digest) -> String {
    markdown(digest, &Config::default())
}

// ---------------------------------------------------------------------------
// The shape of a session
// ---------------------------------------------------------------------------

#[test]
fn an_empty_session_says_so_rather_than_printing_a_blank_screen() {
    let digest = digest(Vec::new(), Vec::new());

    let report = plain(&digest);
    assert!(report.contains("standup"), "{report}");
    assert!(
        flatten(&report).contains("No repositories were found"),
        "{report}"
    );
    assert!(report.lines().count() >= 2, "{report}");

    let pasted = md(&digest);
    assert!(
        flatten(&pasted).contains("No repositories were found"),
        "{pasted}"
    );
}

#[test]
fn the_header_states_the_window_and_its_zone() {
    let report = plain(&digest(vec![busy_repo()], Vec::new()));
    let header = report.lines().next().unwrap();

    assert!(header.contains("2026-08-15 00:00 CEST +0200"), "{header}");
    // The day and the zone are established once, so "generated" may be a bare
    // time — but it must be there.
    assert!(header.contains("generated 09:12"), "{header}");
}

#[test]
fn a_bounded_window_states_both_of_its_ends() {
    let mut digest = digest(vec![busy_repo()], Vec::new());
    digest.window.until = Some(stamp("2026-08-15 12:00", 1_786_043_000));

    let report = flatten(&plain(&digest));
    assert!(
        report.contains("since 2026-08-15 00:00 CEST +0200"),
        "{report}"
    );
    assert!(
        report.contains("until 2026-08-15 12:00 CEST +0200"),
        "{report}"
    );
}

#[test]
fn every_repository_quiet_is_one_line_not_three_zeros() {
    let digest = digest(
        vec![quiet_repo("alpha"), quiet_repo("beta"), quiet_repo("gamma")],
        Vec::new(),
    );

    let report = plain(&digest);
    let flat = flatten(&report);
    assert!(flat.contains("quiet: alpha, beta, gamma"), "{report}");
    assert!(flat.contains("across 3 repositories"), "{report}");
    // Nothing is padded out with zeros, and nothing is silently dropped.
    assert!(!report.contains("0 commits"), "{report}");
    assert!(!report.contains(&format!("+0 {MINUS}0")), "{report}");

    let pasted = flatten(&md(&digest));
    assert!(pasted.contains("Quiet: alpha, beta, gamma."), "{pasted}");
}

#[test]
fn one_busy_repository_and_three_quiet_ones() {
    let digest = digest(
        vec![
            quiet_repo("brambleway"),
            busy_repo(),
            quiet_repo("quillmark"),
            quiet_repo("solstice"),
        ],
        Vec::new(),
    );

    let report = plain(&digest);
    assert!(report.contains("lanternfish"), "{report}");
    assert!(
        flatten(&report).contains("quiet: brambleway, quillmark, solstice"),
        "{report}"
    );
    // A quiet repository costs exactly one mention: no heading of its own.
    for name in ["brambleway", "quillmark", "solstice"] {
        assert_eq!(report.matches(name).count(), 1, "{name} in:\n{report}");
    }
}

#[test]
fn a_quiet_checkout_inside_a_busy_repository_still_says_quiet() {
    let mut busy = busy_repo();
    busy.checkouts
        .push(alone(checkout("/repos/lanternfish", "main")));
    let digest = digest(vec![busy], Vec::new());

    let report = plain(&digest);
    let quiet_line = line_with(&report, "quiet");
    assert!(quiet_line.trim() == "quiet", "{report}");

    let pasted = md(&digest);
    assert!(pasted.contains("`main`"), "{pasted}");
    assert!(pasted.contains("quiet"), "{pasted}");
}

#[test]
fn a_broken_checkout_sorts_first_and_shows_its_problems() {
    let mut broken = checkout("/repos/zulu", "main");
    broken.problems = vec![
        "git rev-list failed: bad object HEAD".to_string(),
        "git diff --numstat timed out after 20s".to_string(),
    ];
    let digest = digest(
        vec![repo("zulu", vec![alone(broken)]), busy_repo()],
        Vec::new(),
    );

    let report = plain(&digest);
    let broken_at = report.find("zulu").expect("broken repo missing");
    let busy_at = report.find("lanternfish").expect("busy repo missing");
    assert!(broken_at < busy_at, "broken must sort first:\n{report}");

    let flat = flatten(&report);
    assert!(
        flat.contains("git rev-list failed: bad object HEAD"),
        "{report}"
    );
    assert!(
        flat.contains("git diff --numstat timed out after 20s"),
        "{report}"
    );

    // Neither may be dropped for brevity in the pasted form either.
    let pasted = flatten(&md(&digest));
    assert!(
        pasted.contains("git rev-list failed: bad object HEAD"),
        "{pasted}"
    );
    assert!(pasted.contains("timed out after 20s"), "{pasted}");
}

#[test]
fn notes_are_always_rendered_whatever_their_severity() {
    let digest = digest(
        vec![busy_repo()],
        vec![
            Note::warning("herdr is not reachable (connection refused)"),
            Note::info("workspace \"scratch\": /tmp/scratch is not a git checkout"),
        ],
    );

    let flat = flatten(&plain(&digest));
    assert!(
        flat.contains("herdr is not reachable (connection refused)"),
        "{flat}"
    );
    assert!(
        flat.contains("/tmp/scratch is not a git checkout"),
        "{flat}"
    );

    let pasted = flatten(&md(&digest));
    assert!(pasted.contains("herdr is not reachable"), "{pasted}");
    assert!(
        pasted.contains("/tmp/scratch is not a git checkout"),
        "{pasted}"
    );
}

#[test]
fn a_note_survives_an_otherwise_empty_session() {
    let digest = digest(
        Vec::new(),
        vec![Note::warning("git could not be run: no such file")],
    );
    let flat = flatten(&plain(&digest));
    assert!(
        flat.contains("git could not be run: no such file"),
        "{flat}"
    );
}

#[test]
fn the_window_explains_itself_when_it_is_not_the_default() {
    let mut explicit = digest(vec![busy_repo()], Vec::new());
    explicit.window.source = WindowSource::Explicit {
        spec: "2 days ago".to_string(),
    };
    assert!(
        flatten(&plain(&explicit)).contains("--since \"2 days ago\""),
        "{}",
        plain(&explicit)
    );

    let mut since_last = digest(vec![busy_repo()], Vec::new());
    since_last.window.source = WindowSource::SinceLast {
        previous_run: stamp("2026-08-14 17:03", 1_785_950_000),
    };
    assert!(
        flatten(&plain(&since_last)).contains("previous run was 2026-08-14 17:03 CEST +0200"),
        "{}",
        plain(&since_last)
    );

    let mut first_run = digest(vec![busy_repo()], Vec::new());
    first_run.window.source = WindowSource::SinceLastFirstRun;
    assert!(
        flatten(&plain(&first_run)).contains("no previous run is on record"),
        "{}",
        plain(&first_run)
    );

    // The default needs no explanation and does not get one.
    assert!(!flatten(&plain(&digest(vec![busy_repo()], Vec::new()))).contains("window from"));
}

// ---------------------------------------------------------------------------
// The vocabulary of one checkout
// ---------------------------------------------------------------------------

#[test]
fn every_head_variant_is_distinguishable() {
    let branch = checkout("/repos/app/one", "feature/one");
    let mut detached = checkout("/repos/app/two", "unused");
    detached.head = Head::Detached {
        oid: "0f0f0f0fdeadbeefcafe112233445566778899aa".to_string(),
    };
    let mut unborn = checkout("/repos/app/three", "unused");
    unborn.head = Head::Unborn {
        name: "main".to_string(),
    };
    let mut deleted = checkout("/repos/app/four", "unused");
    deleted.head = Head::BranchDeleted {
        name: "feature/gone".to_string(),
    };

    // One commit each, so the block is rendered rather than summarised away.
    let commits = || {
        vec![commit(
            "cafe0001cafe0001cafe0001cafe0001cafe0001",
            "2026-08-15 08:00",
            1_786_028_400,
            "Something happened",
            &["a.rs"],
        )]
    };
    let digest = digest(
        vec![repo(
            "app",
            vec![
                alone(with_commits(branch, commits())),
                alone(with_commits(detached, commits())),
                alone(unborn),
                alone(deleted),
            ],
        )],
        Vec::new(),
    );

    let report = plain(&digest);
    let flat = flatten(&report);
    assert!(report.contains("feature/one"), "{report}");
    assert!(report.contains("(detached at 0f0f0f0f)"), "{report}");
    assert!(flat.contains("unborn branch"), "{report}");
    assert!(
        flat.contains("branch feature/gone was deleted underneath this checkout"),
        "{report}"
    );
    // A deleted branch is a problem, and is marked as one rather than blending
    // into the quiet checkouts.
    assert!(line_with(&report, "was deleted").contains('!'), "{report}");
}

#[test]
fn every_tracking_variant_gets_its_own_sentence() {
    let variants = vec![
        (Tracking::NotApplicable, "no branch to track"),
        (Tracking::NoUpstream, "no upstream"),
        (
            Tracking::UpstreamMissing {
                name: "origin/gone".to_string(),
            },
            "upstream origin/gone no longer exists",
        ),
        (
            Tracking::Upstream {
                name: "origin/main".to_string(),
                ahead: 0,
                behind: 0,
            },
            "in sync with origin/main",
        ),
        (
            Tracking::Upstream {
                name: "origin/main".to_string(),
                ahead: 3,
                behind: 0,
            },
            "3 ahead of origin/main",
        ),
        (
            Tracking::Upstream {
                name: "origin/main".to_string(),
                ahead: 0,
                behind: 2,
            },
            "2 behind origin/main",
        ),
        (
            Tracking::Upstream {
                name: "origin/main".to_string(),
                ahead: 3,
                behind: 2,
            },
            "3 ahead, 2 behind origin/main",
        ),
    ];

    let mut sentences: Vec<&str> = Vec::new();
    for (index, (tracking, expected)) in variants.into_iter().enumerate() {
        let mut report = checkout(&format!("/repos/app/w{index}"), &format!("branch-{index}"));
        report.tracking = tracking;
        let report = with_commits(
            report,
            vec![commit(
                "aaaa0001aaaa0001aaaa0001aaaa0001aaaa0001",
                "2026-08-15 08:00",
                1_786_028_400,
                "Work",
                &["a.rs"],
            )],
        );
        let digest = digest(vec![repo("app", vec![alone(report)])], Vec::new());

        let flat = flatten(&plain(&digest));
        assert!(flat.contains(expected), "expected {expected:?} in:\n{flat}");
        assert!(flat.contains(expected), "{flat}");
        sentences.push(expected);
    }

    // Distinct states must not collapse into the same words.
    for (index, one) in sentences.iter().enumerate() {
        for other in sentences.iter().skip(index + 1) {
            assert_ne!(one, other);
        }
    }
}

#[test]
fn every_landed_variant_gets_its_own_sentence_and_never_a_bare_false() {
    let landed = vec![
        (
            Landed::IsDefault {
                name: "main".to_string(),
            },
            "on the default branch main",
        ),
        (
            Landed::Merged {
                into: "origin/main".to_string(),
            },
            "merged into origin/main",
        ),
        (
            Landed::Equivalent {
                into: "origin/main".to_string(),
                how: Equivalence::EveryCommit { commits: 3 },
            },
            "every commit is on origin/main by patch, not by sha",
        ),
        (
            Landed::Equivalent {
                into: "origin/main".to_string(),
                how: Equivalence::Squashed {
                    oid: "6df5ff43f499b52033c34557418e036589a1854c".to_string(),
                },
            },
            "on origin/main by patch as 6df5ff43, not by sha",
        ),
        (
            Landed::NotMerged {
                into: "origin/main".to_string(),
            },
            "not merged into origin/main",
        ),
        (
            Landed::Unknown {
                reason: "no default branch to compare against".to_string(),
            },
            "merge status unknown: no default branch to compare against",
        ),
    ];
    // Every variant renders into an otherwise identical digest — same path,
    // same branch, same commit — so the whole rendered report differs only by
    // the landed clause, and comparing reports *is* comparing the sentences.
    // Collecting the expectations instead would only prove the author typed
    // eight distinct literals, and it would miss the case that matters:
    // `"merged into origin/main"` is a substring of `"not merged into
    // origin/main"`, so `Merged` collapsing into `NotMerged` satisfies
    // `contains` on its own.
    let mut rendered = Vec::new();
    for (state, expected) in landed {
        let mut report = checkout("/repos/app/w", "branch");
        report.landed = state;
        let report = with_commits(
            report,
            vec![commit(
                "bbbb0001bbbb0001bbbb0001bbbb0001bbbb0001",
                "2026-08-15 08:00",
                1_786_028_400,
                "Work",
                &["a.rs"],
            )],
        );
        let digest = digest(vec![repo("app", vec![alone(report)])], Vec::new());

        let report = plain(&digest);
        let flat = flatten(&report);
        assert!(flat.contains(expected), "{report}");
        assert!(!report.contains("false"), "{report}");
        assert!(!md(&digest).contains("false"), "{}", md(&digest));
        rendered.push(flat);
    }

    // A patch match is evidence and containment is proof, so the two must not
    // reach the reader in the same words. Nor may any other pair collapse.
    for (index, one) in rendered.iter().enumerate() {
        for other in rendered.iter().skip(index + 1) {
            assert_ne!(one, other, "two landed states rendered identically");
        }
    }
}

#[test]
fn uncommitted_work_is_reported_as_a_present_tense_fact() {
    let mut report = checkout("/repos/app/w", "feature/wip");
    report.dirty = Dirty {
        tracked_changed: 3,
        untracked: 2,
        conflicted: 1,
        insertions: 40,
        deletions: 2,
    };
    let digest = digest(vec![repo("app", vec![alone(report)])], Vec::new());

    let flat = flatten(&plain(&digest));
    assert!(flat.contains("uncommitted:"), "{flat}");
    assert!(flat.contains("3 files changed"), "{flat}");
    assert!(flat.contains("2 untracked"), "{flat}");
    assert!(flat.contains("1 file conflicted"), "{flat}");
    assert!(flat.contains(&format!("+40 {MINUS}2")), "{flat}");
    // Uncommitted work is not quiet, and must not be summarised away.
    assert!(!flat.contains("quiet:"), "{flat}");
}

#[test]
fn agents_are_named_and_their_session_ids_are_not() {
    let report = with_commits(
        checkout("/repos/app/w", "feature/one"),
        vec![commit(
            "cccc0001cccc0001cccc0001cccc0001cccc0001",
            "2026-08-15 08:00",
            1_786_028_400,
            "Work",
            &["a.rs"],
        )],
    );
    let checkout_digest = worked_by(
        report,
        vec![
            agent("w1:p1", Some("kestrel"), Some("opencode")),
            agent("w1:p2", None, Some("claude")),
        ],
    );
    let digest = digest(vec![repo("app", vec![checkout_digest])], Vec::new());

    let flat = flatten(&plain(&digest));
    assert!(flat.contains("kestrel (opencode)"), "{flat}");
    assert!(flat.contains("claude"), "{flat}");
    // The session id is a pointer for follow-up, not something to paste into a
    // team channel.
    assert!(!flat.contains("session-7f3a"), "{flat}");
    assert!(!md(&digest).contains("session-7f3a"));
}

/// #19, as a reader sees it. Two agents herdr never named, in one checkout, in
/// one window. They share a display label, so deduplicating attribution by name
/// reported them as one and silently halved the day's participants.
///
/// Both are credited, and the count is on the label rather than the label being
/// repeated: `claude, claude` reads like a rendering bug, where `claude ×2`
/// reads like the fact it is.
#[test]
fn two_agents_sharing_a_label_are_both_credited() {
    let report = with_commits(
        checkout("/repos/app/w", "feature/one"),
        vec![commit(
            "eeee0001eeee0001eeee0001eeee0001eeee0001",
            "2026-08-15 08:00",
            1_786_028_400,
            "Work",
            &["a.rs"],
        )],
    );
    let checkout_digest = worked_by(
        report,
        vec![
            agent("w1:p1", None, Some("claude")),
            agent("w1:p2", None, Some("claude")),
        ],
    );
    let digest = digest(vec![repo("app", vec![checkout_digest])], Vec::new());

    for rendered in [plain(&digest), md(&digest)] {
        let flat = flatten(&rendered);
        assert!(
            flat.contains(&format!("agents: claude {TIMES}2")),
            "two agents must not read as one:\n{rendered}"
        );
    }
}

/// The other half of the same rule: a count only appears where there is
/// something to count.
#[test]
fn a_single_agent_is_not_given_a_count() {
    let report = with_commits(
        checkout("/repos/app/w", "feature/one"),
        vec![commit(
            "ffff0001ffff0001ffff0001ffff0001ffff0001",
            "2026-08-15 08:00",
            1_786_028_400,
            "Work",
            &["a.rs"],
        )],
    );
    let checkout_digest = worked_by(
        report,
        vec![agent("w1:p1", Some("kestrel"), Some("claude"))],
    );
    let digest = digest(vec![repo("app", vec![checkout_digest])], Vec::new());

    let flat = flatten(&plain(&digest));
    assert!(flat.contains("agents: kestrel (claude)"), "{flat}");
    assert!(!flat.contains(TIMES), "{flat}");
}

#[test]
fn a_checkout_with_no_workspace_left_still_credits_its_authors() {
    // A sibling worktree whose agent finished and whose workspace was closed.
    let report = with_commits(
        checkout("/repos/app/w", "feature/one"),
        vec![commit(
            "dddd0001dddd0001dddd0001dddd0001dddd0001",
            "2026-08-15 08:00",
            1_786_028_400,
            "Work",
            &["a.rs"],
        )],
    );
    let digest = digest(vec![repo("app", vec![alone(report)])], Vec::new());
    assert!(flatten(&plain(&digest)).contains("authors: Agent Smith"));
}

#[test]
fn merges_are_counted_and_explained_rather_than_silently_changing_the_churn() {
    let mut merge = commit(
        "eeee0001eeee0001eeee0001eeee0001eeee0001",
        "2026-08-15 09:00",
        1_786_032_000,
        "Merge branch 'feature/one'",
        &[],
    );
    merge.is_merge = true;
    merge.insertions = 0;
    merge.deletions = 0;

    let report = with_commits(
        checkout("/repos/app/w", "main"),
        vec![
            merge,
            commit(
                "ffff0001ffff0001ffff0001ffff0001ffff0001",
                "2026-08-15 08:00",
                1_786_028_400,
                "Work",
                &["a.rs"],
            ),
        ],
    );
    let digest = digest(vec![repo("app", vec![alone(report)])], Vec::new());

    let flat = flatten(&plain(&digest));
    assert!(flat.contains("2 commits (1 merge)"), "{flat}");
}

// ---------------------------------------------------------------------------
// Counting in English
// ---------------------------------------------------------------------------

#[test]
fn counts_read_as_english_in_the_singular() {
    let report = with_commits(
        checkout("/repos/app/w", "feature/one"),
        vec![commit(
            "1111000111110001111100011111000111110001",
            "2026-08-15 08:00",
            1_786_028_400,
            "One thing",
            &["a.rs"],
        )],
    );
    let digest = digest(vec![repo("app", vec![alone(report)])], Vec::new());

    for rendered in [plain(&digest), md(&digest)] {
        assert!(rendered.contains("1 commit"), "{rendered}");
        assert!(rendered.contains("1 file"), "{rendered}");
        assert!(!rendered.contains("1 commits"), "{rendered}");
        assert!(!rendered.contains("1 files"), "{rendered}");
        assert!(!rendered.contains("1 repositories"), "{rendered}");
    }
}

#[test]
fn counts_read_as_english_in_the_plural() {
    let digest = digest(vec![busy_repo(), quiet_repo("solstice")], Vec::new());
    for rendered in [plain(&digest), md(&digest)] {
        assert!(rendered.contains("2 commits"), "{rendered}");
        assert!(rendered.contains("3 files"), "{rendered}");
        assert!(rendered.contains("2 repositories"), "{rendered}");
        assert!(!rendered.contains("2 commit "), "{rendered}");
    }
}

// ---------------------------------------------------------------------------
// Time
// ---------------------------------------------------------------------------

#[test]
fn commit_lines_inside_one_day_carry_the_time_alone() {
    let report = plain(&digest(vec![busy_repo()], Vec::new()));
    let commit_line = line_with(&report, "a1b2c3d4");

    assert!(commit_line.contains("09:04"), "{commit_line}");
    // The header has already established the day; repeating it on every line
    // costs eleven columns of subject.
    assert!(!commit_line.contains("2026-08-15"), "{commit_line}");
}

#[test]
fn commit_lines_carry_the_date_once_the_window_spans_more_than_a_day() {
    let mut digest = digest(vec![busy_repo()], Vec::new());
    digest.window.since = stamp("2026-08-13 00:00", 1_785_800_000);
    digest.repos[0].checkouts[0].report.commits[1].committed =
        stamp("2026-08-14 17:40", 1_785_950_000);

    let report = plain(&digest);
    assert!(
        line_with(&report, "a1b2c3d4").contains("2026-08-15 09:04"),
        "{report}"
    );
    assert!(
        line_with(&report, "b2c3d4e5").contains("2026-08-14 17:40"),
        "{report}"
    );

    let pasted = md(&digest);
    assert!(pasted.contains("2026-08-14 17:40"), "{pasted}");
}

#[test]
fn a_commit_dated_outside_the_header_day_forces_the_date_on() {
    // The window is one day wide, but a commit is not from it. Better to print
    // a date nobody needed than to imply a day the commit is not from.
    let mut digest = digest(vec![busy_repo()], Vec::new());
    digest.repos[0].checkouts[0].report.commits[1].committed =
        stamp("2026-08-14 23:59", 1_785_970_000);

    let report = plain(&digest);
    assert!(
        line_with(&report, "a1b2c3d4").contains("2026-08-15 09:04"),
        "{report}"
    );
}

// ---------------------------------------------------------------------------
// Eighty columns
// ---------------------------------------------------------------------------

/// A branch of 90 characters, a path 200 characters deep and a subject of 300.
fn monstrous() -> Digest {
    let branch = format!("feat/{}", "throughput-".repeat(8));
    assert!(branch.len() >= 90, "fixture must exceed the branch column");
    let deep: String = (0..25)
        .map(|n| format!("/segment-number-{n}"))
        .collect::<Vec<_>>()
        .join("");
    assert!(deep.len() >= 200, "fixture must exceed the path budget");
    let subject = "y".repeat(300);

    let mut report = checkout(&deep, &branch);
    report.tracking = Tracking::Upstream {
        name: "origin/feat/a-very-long-remote-branch-name-indeed".to_string(),
        ahead: 4,
        behind: 0,
    };
    report.landed = Landed::NotMerged {
        into: "origin/a-very-long-default-branch-name".to_string(),
    };
    let mut only = commit(
        "9999888877776666555544443333222211110000",
        "2026-08-15 09:04",
        1_786_032_240,
        &subject,
        &["src/a.rs"],
    );
    only.insertions = 123_456;
    only.deletions = 98_765;

    digest(
        vec![repo(
            &"repository-with-an-unreasonably-long-name".repeat(3),
            vec![alone(with_commits(report, vec![only]))],
        )],
        vec![Note::warning(
            "a warning long enough to need wrapping: the worktree list for this \
             repository could not be read, so sibling checkouts are missing from \
             the numbers above",
        )],
    )
}

#[test]
fn nothing_wraps_into_soup_at_eighty_columns() {
    let digest = monstrous();
    let report = plain(&digest);

    assert!(widest(&report) <= WIDTH, "widest line:\n{report}");
    assert!(report.contains(ELLIPSIS), "something must be marked as cut");
    // The cut is marked, not silent, and the object id keeps its fixed width.
    assert!(report.contains("99998888"), "{report}");
}

#[test]
fn numbers_are_never_truncated() {
    let report = plain(&monstrous());
    assert!(
        report.contains(&format!("+123456 {MINUS}98765")),
        "{report}"
    );
    assert!(widest(&report) <= WIDTH, "{report}");
}

#[test]
fn a_long_path_is_cut_in_the_middle_and_a_long_branch_at_the_end() {
    let report = plain(&monstrous());

    let branch_line = line_with(&report, "feat/throughput-");
    // The branch keeps its head and loses its tail...
    assert!(branch_line.contains("feat/throughput-"), "{branch_line}");
    // ...while the path keeps its tail, which is the half that identifies it.
    assert!(branch_line.contains("segment-number-24"), "{branch_line}");
    assert!(branch_line.contains(ELLIPSIS), "{branch_line}");
}

#[test]
fn a_home_relative_path_is_preferred_to_an_absolute_one() {
    let home = std::env::var("HOME").expect("these tests need a HOME");
    let report = with_commits(
        checkout(&format!("{home}/repos/app"), "main"),
        vec![commit(
            "2222000122220001222200012222000122220001",
            "2026-08-15 08:00",
            1_786_028_400,
            "Work",
            &["a.rs"],
        )],
    );
    let digest = digest(vec![repo("app", vec![alone(report)])], Vec::new());

    let rendered = plain(&digest);
    assert!(rendered.contains("~/repos/app"), "{rendered}");
    assert!(!rendered.contains(&home), "{rendered}");
    assert!(md(&digest).contains("~/repos/app"));
}

// ---------------------------------------------------------------------------
// max_commits
// ---------------------------------------------------------------------------

fn five_commits() -> Digest {
    let commits: Vec<Commit> = (0..5)
        .map(|n| {
            commit(
                &format!("{n}{n}{n}{n}0001").repeat(5),
                &format!("2026-08-15 0{}:00", n + 1),
                1_786_028_400 + i64::from(n) * 3_600,
                &format!("Commit number {n}"),
                &["a.rs"],
            )
        })
        .collect();
    let report = with_commits(checkout("/repos/app/w", "feature/one"), commits);
    digest(vec![repo("app", vec![alone(report)])], Vec::new())
}

#[test]
fn the_commits_that_do_not_fit_are_counted_never_dropped() {
    let digest = five_commits();
    let config = Config {
        max_commits: 2,
        ..Config::default()
    };

    let report = text(&digest, &config);
    let flat = flatten(&report);
    assert!(flat.contains("3 more commits not listed"), "{report}");
    // The newest survive, the oldest are the ones counted.
    assert!(report.contains("Commit number 4"), "{report}");
    assert!(report.contains("Commit number 3"), "{report}");
    assert!(!report.contains("Commit number 0"), "{report}");
    // The total is still stated in full.
    assert!(flat.contains("5 commits"), "{report}");

    let pasted = flatten(&markdown(&digest, &config));
    assert!(pasted.contains("3 more commits not listed"), "{pasted}");
    assert!(pasted.contains("5 commits"), "{pasted}");
}

#[test]
fn listing_no_commits_at_all_still_reports_how_many_there_were() {
    let digest = five_commits();
    let config = Config {
        max_commits: 0,
        ..Config::default()
    };
    let flat = flatten(&text(&digest, &config));
    assert!(flat.contains("5 commits not listed"), "{flat}");
    assert!(!flat.contains("Commit number"), "{flat}");
}

#[test]
fn a_single_held_back_commit_is_counted_in_the_singular() {
    let digest = five_commits();
    let config = Config {
        max_commits: 4,
        ..Config::default()
    };
    let flat = flatten(&text(&digest, &config));
    assert!(flat.contains("1 more commit not listed"), "{flat}");
    assert!(!flat.contains("1 more commits"), "{flat}");
}

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------

/// Branch names, agent names and subjects that contain what Markdown treats as
/// syntax. Every one of these occurs in real repositories.
fn awkward() -> Digest {
    let mut one = with_commits(
        checkout("/repos/app/one", "feat/re[factor]"),
        vec![commit(
            "aaaa1111aaaa1111aaaa1111aaaa1111aaaa1111",
            "2026-08-15 09:00",
            1_786_032_000,
            "Fix the `render` path",
            &["a.rs"],
        )],
    );
    one.tracking = Tracking::Upstream {
        name: "origin/feat/re[factor]".to_string(),
        ahead: 1,
        behind: 0,
    };

    let two = with_commits(
        checkout("/repos/app/two", "a|b"),
        vec![commit(
            "bbbb1111bbbb1111bbbb1111bbbb1111bbbb1111",
            "2026-08-15 08:00",
            1_786_028_400,
            "# oops",
            &["b.rs"],
        )],
    );

    let three = with_commits(
        checkout("/repos/app/three", "fix_*_thing"),
        vec![commit(
            "cccc1111cccc1111cccc1111cccc1111cccc1111",
            "2026-08-15 07:00",
            1_786_024_800,
            "Escape <b>bold</b> and a pipe | too",
            &["c.rs"],
        )],
    );

    let four = with_commits(
        checkout("/repos/app/four", "`weird`"),
        vec![commit(
            "dddd1111dddd1111dddd1111dddd1111dddd1111",
            "2026-08-15 06:00",
            1_786_021_200,
            "sub`ject",
            &["d.rs"],
        )],
    );

    let five = with_commits(
        checkout("/repos/app/five", "fix``double"),
        vec![commit(
            "eeee1111eeee1111eeee1111eeee1111eeee1111",
            "2026-08-15 05:00",
            1_786_017_600,
            "1. not a list",
            &["e.rs"],
        )],
    );

    digest(
        vec![repo(
            "app",
            vec![
                alone(one),
                alone(two),
                alone(three),
                alone(four),
                alone(five),
            ],
        )],
        Vec::new(),
    )
}

#[test]
fn markdown_fences_branch_names_that_contain_syntax() {
    let pasted = md(&awkward());

    assert!(pasted.contains("`feat/re[factor]`"), "{pasted}");
    assert!(pasted.contains("`a|b`"), "{pasted}");
    assert!(pasted.contains("`fix_*_thing`"), "{pasted}");
}

#[test]
fn markdown_lengthens_the_fence_for_a_name_containing_backticks() {
    let pasted = md(&awkward());

    // A name that both starts and ends with a backtick needs the padding rule
    // as well as the longer fence.
    assert!(pasted.contains("`` `weird` ``"), "{pasted}");
    // Two backticks inside means at least three around.
    assert!(pasted.contains("```fix``double```"), "{pasted}");
}

#[test]
fn markdown_escapes_subjects_rather_than_fencing_them() {
    let pasted = md(&awkward());

    // A backtick in a subject would end an inline code span, so subjects are
    // escaped prose instead.
    assert!(pasted.contains("sub\\`ject"), "{pasted}");
    assert!(pasted.contains("Fix the \\`render\\` path"), "{pasted}");
}

#[test]
fn markdown_never_lets_a_subject_become_a_heading_or_a_list() {
    let pasted = md(&awkward());

    assert!(pasted.contains("\\# oops"), "{pasted}");
    for line in pasted.lines() {
        assert!(
            !line.trim_start().starts_with("# "),
            "heading in:\n{pasted}"
        );
    }
    assert!(pasted.contains("1\\. not a list"), "{pasted}");
}

#[test]
fn markdown_emits_no_html_and_no_tables() {
    let pasted = md(&awkward());

    // Angle brackets survive as text, escaped; none of them opens a tag.
    assert!(pasted.contains("\\<b\\>bold\\</b\\>"), "{pasted}");
    for tag in ["<b>", "<br", "<div", "<table", "<span"] {
        assert!(!pasted.contains(tag), "{tag} in:\n{pasted}");
    }
    // A pipe in a cell breaks a table, so there are no tables to break.
    assert!(!pasted.contains("|---"), "{pasted}");
    assert!(!pasted.contains("--- |"), "{pasted}");
    for line in pasted.lines() {
        assert!(
            !line.trim_start().starts_with('|'),
            "table row in:\n{pasted}"
        );
    }
}

#[test]
fn markdown_stays_a_nested_list_that_survives_a_paste() {
    let digest = digest(vec![busy_repo(), quiet_repo("solstice")], Vec::new());
    let pasted = md(&digest);

    assert!(pasted.starts_with("**standup**"), "{pasted}");
    assert!(pasted.contains("\n- **lanternfish**"), "{pasted}");
    assert!(pasted.contains("\n  - "), "{pasted}");
    assert!(pasted.contains("\n    - "), "{pasted}");
    assert!(pasted.trim_end().ends_with("Quiet: solstice."), "{pasted}");
    // Short enough to paste: one bullet per repository, one per checkout, one
    // per commit, and a single trailing line for the quiet ones.
    assert!(pasted.lines().count() < 20, "{pasted}");
}

// ---------------------------------------------------------------------------
// JSON, and the three formats agreeing
// ---------------------------------------------------------------------------

#[test]
fn json_pins_its_top_level_keys_and_its_schema_version() {
    let digest = digest(vec![busy_repo()], vec![Note::info("a note")]);
    let rendered = json(&digest).unwrap();
    let value: serde_json::Value = serde_json::from_str(&rendered).unwrap();

    let mut keys: Vec<&str> = value
        .as_object()
        .expect("top level must be an object")
        .keys()
        .map(String::as_str)
        .collect();
    keys.sort_unstable();
    assert_eq!(keys, ["generated_at", "notes", "repos", "schema", "window"]);

    assert_eq!(value["schema"], serde_json::json!(SCHEMA_VERSION));
    assert_eq!(value["schema"], serde_json::json!(1));

    // The tagged enums keep their discriminators, which is what a script reads.
    assert_eq!(value["window"]["source"]["kind"], "default");
    assert_eq!(value["repos"][0]["checkouts"][0]["head"]["kind"], "branch");
    assert_eq!(
        value["repos"][0]["checkouts"][0]["landed"]["kind"],
        "unknown"
    );
    assert_eq!(
        value["repos"][0]["checkouts"][0]["tracking"]["kind"],
        "no_upstream"
    );
    // `CheckoutReport` is flattened into the checkout, not nested under a key.
    assert!(value["repos"][0]["checkouts"][0]["path"].is_string());
    assert_eq!(value["notes"][0]["severity"], "info");
}

/// The nested tag a script reads to tell a squash landing from an exact one,
/// and the sha it reads to check the claim by hand.
///
/// `landed.how` is a tagged enum inside a tagged enum, which is the one shape
/// nothing else in the JSON has, and the sha lives at `landed.how.oid` rather
/// than beside `kind`.
#[test]
fn json_carries_the_matched_trunk_sha_for_an_equivalent_landing() {
    let mut report = checkout("/repos/app/w", "feature/squashed");
    report.landed = Landed::Equivalent {
        into: "origin/main".to_string(),
        how: Equivalence::Squashed {
            oid: "6df5ff43f499b52033c34557418e036589a1854c".to_string(),
        },
    };
    let squashed = digest(vec![repo("app", vec![alone(report)])], Vec::new());
    let value: serde_json::Value = serde_json::from_str(&json(&squashed).unwrap()).unwrap();
    let landed = &value["repos"][0]["checkouts"][0]["landed"];

    assert_eq!(landed["kind"], "equivalent");
    assert_eq!(landed["into"], "origin/main");
    assert_eq!(landed["how"]["kind"], "squashed");
    assert_eq!(
        landed["how"]["oid"],
        "6df5ff43f499b52033c34557418e036589a1854c"
    );

    // The other reading carries a count and no sha, because no single trunk
    // commit is the one that matched.
    let mut report = checkout("/repos/app/w", "feature/rebased");
    report.landed = Landed::Equivalent {
        into: "origin/main".to_string(),
        how: Equivalence::EveryCommit { commits: 3 },
    };
    let rebased = digest(vec![repo("app", vec![alone(report)])], Vec::new());
    let value: serde_json::Value = serde_json::from_str(&json(&rebased).unwrap()).unwrap();
    let landed = &value["repos"][0]["checkouts"][0]["landed"];

    assert_eq!(landed["how"]["kind"], "every_commit");
    assert_eq!(landed["how"]["commits"], 3);
    assert!(landed["how"]["oid"].is_null());
}

#[test]
fn all_three_formats_agree_on_the_totals() {
    let digest = digest(
        vec![
            busy_repo(),
            quiet_repo("solstice"),
            quiet_repo("brambleway"),
        ],
        Vec::new(),
    );

    let value: serde_json::Value = serde_json::from_str(&json(&digest).unwrap()).unwrap();
    let repos = value["repos"].as_array().unwrap();
    let commits: u64 = repos.iter().map(|r| r["commits"].as_u64().unwrap()).sum();
    let files: u64 = repos
        .iter()
        .map(|r| r["churn"]["files"].as_u64().unwrap())
        .sum();
    let insertions: u64 = repos
        .iter()
        .map(|r| r["churn"]["insertions"].as_u64().unwrap())
        .sum();
    let deletions: u64 = repos
        .iter()
        .map(|r| r["churn"]["deletions"].as_u64().unwrap())
        .sum();

    let report = plain(&digest);
    let pasted = md(&digest);
    for rendered in [&report, &pasted] {
        assert!(
            rendered.contains(&format!("{commits} commits")),
            "{rendered}"
        );
        assert!(rendered.contains(&format!("{files} files")), "{rendered}");
        assert!(
            rendered.contains(&format!("+{insertions} {MINUS}{deletions}")),
            "{rendered}"
        );
    }

    // And the count of repositories in the JSON is the count both prose forms
    // claim, quiet ones included.
    assert!(report.contains(&format!("across {} repositories", repos.len())));
    assert!(pasted.contains(&format!("across {} repositories", repos.len())));
}

#[test]
fn the_kitchen_sink_renders_in_all_three_formats_without_losing_anything() {
    let mut digest = monstrous();
    digest.repos.push(busy_repo());
    digest.repos.push(quiet_repo("solstice"));
    let mut broken = checkout("/repos/broken", "main");
    broken.problems = vec!["git worktree list failed".to_string()];
    digest.repos.push(repo("broken", vec![alone(broken)]));

    let report = plain(&digest);
    assert!(widest(&report) <= WIDTH, "{report}");
    assert!(
        flatten(&report).contains("git worktree list failed"),
        "{report}"
    );
    assert!(flatten(&report).contains("quiet: solstice"), "{report}");

    let pasted = md(&digest);
    assert!(
        flatten(&pasted).contains("git worktree list failed"),
        "{pasted}"
    );
    assert!(pasted.contains("Quiet: solstice."), "{pasted}");

    let rendered = json(&digest).unwrap();
    let value: serde_json::Value = serde_json::from_str(&rendered).unwrap();
    assert_eq!(value["repos"].as_array().unwrap().len(), 4);
}
